# Generated by Django 5.1.4 on 2024-12-22 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
